#values.yaml

kind: "Deployment"

# Kubernetes 1.25+
# podsecuritypolicy has been deprecated for this version up.
podSecurityPolicy:
  enabled: false

# # Only applicable for Deployment or StatefulSet
replicaCount: 3
volumes:
- name: elastic-certs
  secret:
    secretName: elastic-certificates
    defaultMode: 0777
volumeMounts:
- name: elastic-certs
  mountPath: /etc/fluent/certs
  readOnly: true

fileConfigs:
  01_sources.conf: |-
      ## logs from podman
      <source>
        @type forward
        @label @KUBE_ALL
        bind 0.0.0.0
        port 24224
      </source>
  02_fileter.conf: |-
    <label @KUBE_ALL>
      <match **>
        @type relabel
        @label @OUTPUT_CONTAINER
      </match>
    </label>

  04_outputs.conf: |-
    <label @OUTPUT_CONTAINER>
      <match **>
        @type elasticsearch
        index_name fluentd-00001
        host "elasticsearch-master"
        port 9200
        path ""
        user elastic
        password password
      </match>
    </label>

  # 04_outputs.conf: |-
  #     <label @OUTPUT_CONTAINER>
  #       <match **>
  #         @type elasticsearch
  #         hosts "https://elastic:password@elasticsearch-master:9200"
  #         index_name fluentd-00001
  #         ca_file /etc/fluent/certs/ca.crt
  #         client_cert /etc/fluent/certs/tls.crt
  #         client_key /etc/fluent/certs/tls.key
  #         #port 9200
  #         #path ""
  #         #user elastic
  #         #password changeme
  #       </match>
  #     </label>