---
elasticsearchHosts: "https://elasticsearch-master:9200"
elasticsearchCertificateSecret: elasticsearch-master-certs
elasticsearchCertificateAuthoritiesFile: ca.crt
elasticsearchCredentialSecret: elasticsearch-master-credentials

replicas: 1


resources:
  requests:
    cpu: "55m"
    memory: "512Mi"
  limits:
    cpu: "250m"
    memory: "2Gi"