apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3

# aws: ebs.csi.aws.com
# minikube: k8s.io/minikube-hostpath
provisioner: k8s.io/minikube-hostpath
parameters:
  type: gp3
  csi.storage.k8s.io/fstype: ext4